from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class CopilotQueryRequest(BaseModel):
    query: str = Field(..., description="User's natural language question about land records")
    user_role: Optional[str] = Field(default=None, description="Current authenticated user role for RBAC enforcement")
    session_id: Optional[str] = Field(default=None, description="Optional conversation session ID")
    filters: Optional[Dict[str, Any]] = Field(default=None, description="Optional explicit query filters")


class CopilotSourceReference(BaseModel):
    record_id: Optional[int] = None
    document_id: Optional[int] = None
    title: str
    survey_number: str
    location: str
    area: Optional[str] = None
    route: str = Field(..., description="Clickable route to the record, e.g. /verification/1")
    gis_route: Optional[str] = None
    document_route: Optional[str] = None


class CopilotFact(BaseModel):
    field: str
    value: Any
    source_record_id: Optional[int] = None


class CopilotPropertyCard(BaseModel):
    record_id: int
    document_id: Optional[int] = None
    survey_number: str
    hissa_number: Optional[str] = None
    village: str
    district: str
    state: str
    owners: List[str] = Field(default_factory=list)
    area_ha: Optional[float] = None
    area_acres: Optional[float] = None
    land_tenure: Optional[str] = None
    validation_status: str
    has_discrepancy: bool = False
    discrepancy_details: Optional[str] = None
    encumbrances: List[str] = Field(default_factory=list)
    mutation_count: int = 0
    view_route: str
    gis_route: Optional[str] = None


class CopilotQueryResponse(BaseModel):
    answer: str = Field(..., description="Evidence-grounded natural language explanation generated by Mistral")
    confidence: str = Field(default="high", description="Confidence level: high, medium, low")
    data_found: bool = Field(default=True, description="Whether verified records were found in the database")
    query: str
    intent: Dict[str, Any] = Field(default_factory=dict, description="Parsed query intent and matched entity filters")
    aggregates: Dict[str, Any] = Field(default_factory=dict, description="Authoritative deterministic database calculations")
    sources: List[CopilotSourceReference] = Field(default_factory=list, description="Clickable source links to verified Land AI records")
    facts: List[CopilotFact] = Field(default_factory=list, description="Extracted factual claims with record traceability")
    properties: List[CopilotPropertyCard] = Field(default_factory=list, description="Structured property summary cards")
    warnings: List[str] = Field(default_factory=list, description="Discrepancy warnings, conflict alerts, or missing data notices")
    requires_review: bool = Field(default=False, description="True if any matched property is flagged for human officer review")
    execution_trace: Dict[str, Any] = Field(default_factory=dict, description="Pipeline execution metadata")


class CopilotSuggestionItem(BaseModel):
    category: str
    query: str
    description: str
    icon: str
